export const TYPES = {
  LOGGER: Symbol.for("LOGGER"),
  ERROR_HANDLER: Symbol.for("ERROR_HANDLER"),
  DB_CONNECTION_OPTIONS: Symbol.for("DB_CONNECTION_OPTIONS"),
  DATABASE: Symbol.for("DATABASE")
};

export const TARGETS = {
  CLUB_SERVICE: Symbol.for("CLUB_SERVICE"),
  DEFAULT_CLUB_SELECTOR: Symbol.for("DEFAULT_CLUB_SELECTOR")
};
